// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: app/log/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xray.App.Log {

  /// <summary>Holder for reflection information generated from app/log/config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for app/log/config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRhcHAvbG9nL2NvbmZpZy5wcm90bxIMeHJheS5hcHAubG9nGhRjb21tb24v",
            "bG9nL2xvZy5wcm90byL6AQoGQ29uZmlnEi0KDmVycm9yX2xvZ190eXBlGAEg",
            "ASgOMhUueHJheS5hcHAubG9nLkxvZ1R5cGUSMgoPZXJyb3JfbG9nX2xldmVs",
            "GAIgASgOMhkueHJheS5jb21tb24ubG9nLlNldmVyaXR5EhYKDmVycm9yX2xv",
            "Z19wYXRoGAMgASgJEi4KD2FjY2Vzc19sb2dfdHlwZRgEIAEoDjIVLnhyYXku",
            "YXBwLmxvZy5Mb2dUeXBlEhcKD2FjY2Vzc19sb2dfcGF0aBgFIAEoCRIWCg5l",
            "bmFibGVfZG5zX2xvZxgGIAEoCBIUCgxtYXNrX2FkZHJlc3MYByABKAkqNQoH",
            "TG9nVHlwZRIICgROb25lEAASCwoHQ29uc29sZRABEggKBEZpbGUQAhIJCgVF",
            "dmVudBADQkYKEGNvbS54cmF5LmFwcC5sb2dQAVohZ2l0aHViLmNvbS94dGxz",
            "L3hyYXktY29yZS9hcHAvbG9nqgIMWHJheS5BcHAuTG9nYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Xray.Common.Log.LogReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Xray.App.Log.LogType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.App.Log.Config), global::Xray.App.Log.Config.Parser, new[]{ "ErrorLogType", "ErrorLogLevel", "ErrorLogPath", "AccessLogType", "AccessLogPath", "EnableDnsLog", "MaskAddress" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LogType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Console")] Console = 1,
    [pbr::OriginalName("File")] File = 2,
    [pbr::OriginalName("Event")] Event = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.App.Log.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config(Config other) : this() {
      errorLogType_ = other.errorLogType_;
      errorLogLevel_ = other.errorLogLevel_;
      errorLogPath_ = other.errorLogPath_;
      accessLogType_ = other.accessLogType_;
      accessLogPath_ = other.accessLogPath_;
      enableDnsLog_ = other.enableDnsLog_;
      maskAddress_ = other.maskAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "error_log_type" field.</summary>
    public const int ErrorLogTypeFieldNumber = 1;
    private global::Xray.App.Log.LogType errorLogType_ = global::Xray.App.Log.LogType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.App.Log.LogType ErrorLogType {
      get { return errorLogType_; }
      set {
        errorLogType_ = value;
      }
    }

    /// <summary>Field number for the "error_log_level" field.</summary>
    public const int ErrorLogLevelFieldNumber = 2;
    private global::Xray.Common.Log.Severity errorLogLevel_ = global::Xray.Common.Log.Severity.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.Common.Log.Severity ErrorLogLevel {
      get { return errorLogLevel_; }
      set {
        errorLogLevel_ = value;
      }
    }

    /// <summary>Field number for the "error_log_path" field.</summary>
    public const int ErrorLogPathFieldNumber = 3;
    private string errorLogPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorLogPath {
      get { return errorLogPath_; }
      set {
        errorLogPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "access_log_type" field.</summary>
    public const int AccessLogTypeFieldNumber = 4;
    private global::Xray.App.Log.LogType accessLogType_ = global::Xray.App.Log.LogType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.App.Log.LogType AccessLogType {
      get { return accessLogType_; }
      set {
        accessLogType_ = value;
      }
    }

    /// <summary>Field number for the "access_log_path" field.</summary>
    public const int AccessLogPathFieldNumber = 5;
    private string accessLogPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccessLogPath {
      get { return accessLogPath_; }
      set {
        accessLogPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enable_dns_log" field.</summary>
    public const int EnableDnsLogFieldNumber = 6;
    private bool enableDnsLog_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableDnsLog {
      get { return enableDnsLog_; }
      set {
        enableDnsLog_ = value;
      }
    }

    /// <summary>Field number for the "mask_address" field.</summary>
    public const int MaskAddressFieldNumber = 7;
    private string maskAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MaskAddress {
      get { return maskAddress_; }
      set {
        maskAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ErrorLogType != other.ErrorLogType) return false;
      if (ErrorLogLevel != other.ErrorLogLevel) return false;
      if (ErrorLogPath != other.ErrorLogPath) return false;
      if (AccessLogType != other.AccessLogType) return false;
      if (AccessLogPath != other.AccessLogPath) return false;
      if (EnableDnsLog != other.EnableDnsLog) return false;
      if (MaskAddress != other.MaskAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ErrorLogType != global::Xray.App.Log.LogType.None) hash ^= ErrorLogType.GetHashCode();
      if (ErrorLogLevel != global::Xray.Common.Log.Severity.Unknown) hash ^= ErrorLogLevel.GetHashCode();
      if (ErrorLogPath.Length != 0) hash ^= ErrorLogPath.GetHashCode();
      if (AccessLogType != global::Xray.App.Log.LogType.None) hash ^= AccessLogType.GetHashCode();
      if (AccessLogPath.Length != 0) hash ^= AccessLogPath.GetHashCode();
      if (EnableDnsLog != false) hash ^= EnableDnsLog.GetHashCode();
      if (MaskAddress.Length != 0) hash ^= MaskAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ErrorLogType != global::Xray.App.Log.LogType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorLogType);
      }
      if (ErrorLogLevel != global::Xray.Common.Log.Severity.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrorLogLevel);
      }
      if (ErrorLogPath.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorLogPath);
      }
      if (AccessLogType != global::Xray.App.Log.LogType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AccessLogType);
      }
      if (AccessLogPath.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AccessLogPath);
      }
      if (EnableDnsLog != false) {
        output.WriteRawTag(48);
        output.WriteBool(EnableDnsLog);
      }
      if (MaskAddress.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(MaskAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ErrorLogType != global::Xray.App.Log.LogType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ErrorLogType);
      }
      if (ErrorLogLevel != global::Xray.Common.Log.Severity.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrorLogLevel);
      }
      if (ErrorLogPath.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorLogPath);
      }
      if (AccessLogType != global::Xray.App.Log.LogType.None) {
        output.WriteRawTag(32);
        output.WriteEnum((int) AccessLogType);
      }
      if (AccessLogPath.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AccessLogPath);
      }
      if (EnableDnsLog != false) {
        output.WriteRawTag(48);
        output.WriteBool(EnableDnsLog);
      }
      if (MaskAddress.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(MaskAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ErrorLogType != global::Xray.App.Log.LogType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorLogType);
      }
      if (ErrorLogLevel != global::Xray.Common.Log.Severity.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorLogLevel);
      }
      if (ErrorLogPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorLogPath);
      }
      if (AccessLogType != global::Xray.App.Log.LogType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AccessLogType);
      }
      if (AccessLogPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessLogPath);
      }
      if (EnableDnsLog != false) {
        size += 1 + 1;
      }
      if (MaskAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MaskAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.ErrorLogType != global::Xray.App.Log.LogType.None) {
        ErrorLogType = other.ErrorLogType;
      }
      if (other.ErrorLogLevel != global::Xray.Common.Log.Severity.Unknown) {
        ErrorLogLevel = other.ErrorLogLevel;
      }
      if (other.ErrorLogPath.Length != 0) {
        ErrorLogPath = other.ErrorLogPath;
      }
      if (other.AccessLogType != global::Xray.App.Log.LogType.None) {
        AccessLogType = other.AccessLogType;
      }
      if (other.AccessLogPath.Length != 0) {
        AccessLogPath = other.AccessLogPath;
      }
      if (other.EnableDnsLog != false) {
        EnableDnsLog = other.EnableDnsLog;
      }
      if (other.MaskAddress.Length != 0) {
        MaskAddress = other.MaskAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ErrorLogType = (global::Xray.App.Log.LogType) input.ReadEnum();
            break;
          }
          case 16: {
            ErrorLogLevel = (global::Xray.Common.Log.Severity) input.ReadEnum();
            break;
          }
          case 26: {
            ErrorLogPath = input.ReadString();
            break;
          }
          case 32: {
            AccessLogType = (global::Xray.App.Log.LogType) input.ReadEnum();
            break;
          }
          case 42: {
            AccessLogPath = input.ReadString();
            break;
          }
          case 48: {
            EnableDnsLog = input.ReadBool();
            break;
          }
          case 58: {
            MaskAddress = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ErrorLogType = (global::Xray.App.Log.LogType) input.ReadEnum();
            break;
          }
          case 16: {
            ErrorLogLevel = (global::Xray.Common.Log.Severity) input.ReadEnum();
            break;
          }
          case 26: {
            ErrorLogPath = input.ReadString();
            break;
          }
          case 32: {
            AccessLogType = (global::Xray.App.Log.LogType) input.ReadEnum();
            break;
          }
          case 42: {
            AccessLogPath = input.ReadString();
            break;
          }
          case 48: {
            EnableDnsLog = input.ReadBool();
            break;
          }
          case 58: {
            MaskAddress = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
