// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proxy/freedom/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xray.Proxy.Freedom {

  /// <summary>Holder for reflection information generated from proxy/freedom/config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for proxy/freedom/config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpwcm94eS9mcmVlZG9tL2NvbmZpZy5wcm90bxISeHJheS5wcm94eS5mcmVl",
            "ZG9tGiFjb21tb24vcHJvdG9jb2wvc2VydmVyX3NwZWMucHJvdG8iSwoTRGVz",
            "dGluYXRpb25PdmVycmlkZRI0CgZzZXJ2ZXIYASABKAsyJC54cmF5LmNvbW1v",
            "bi5wcm90b2NvbC5TZXJ2ZXJFbmRwb2ludCKIAQoIRnJhZ21lbnQSFAoMcGFj",
            "a2V0c19mcm9tGAEgASgEEhIKCnBhY2tldHNfdG8YAiABKAQSEgoKbGVuZ3Ro",
            "X21pbhgDIAEoBBISCgpsZW5ndGhfbWF4GAQgASgEEhQKDGludGVydmFsX21p",
            "bhgFIAEoBBIUCgxpbnRlcnZhbF9tYXgYBiABKAQiaAoFTm9pc2USEgoKbGVu",
            "Z3RoX21pbhgBIAEoBBISCgpsZW5ndGhfbWF4GAIgASgEEhEKCWRlbGF5X21p",
            "bhgDIAEoBBIRCglkZWxheV9tYXgYBCABKAQSEQoJc3RyX25vaXNlGAUgASgM",
            "IsYDCgZDb25maWcSQgoPZG9tYWluX3N0cmF0ZWd5GAEgASgOMikueHJheS5w",
            "cm94eS5mcmVlZG9tLkNvbmZpZy5Eb21haW5TdHJhdGVneRJFChRkZXN0aW5h",
            "dGlvbl9vdmVycmlkZRgDIAEoCzInLnhyYXkucHJveHkuZnJlZWRvbS5EZXN0",
            "aW5hdGlvbk92ZXJyaWRlEhIKCnVzZXJfbGV2ZWwYBCABKA0SLgoIZnJhZ21l",
            "bnQYBSABKAsyHC54cmF5LnByb3h5LmZyZWVkb20uRnJhZ21lbnQSFgoOcHJv",
            "eHlfcHJvdG9jb2wYBiABKA0SKQoGbm9pc2VzGAcgAygLMhkueHJheS5wcm94",
            "eS5mcmVlZG9tLk5vaXNlIqkBCg5Eb21haW5TdHJhdGVneRIJCgVBU19JUxAA",
            "EgoKBlVTRV9JUBABEgsKB1VTRV9JUDQQAhILCgdVU0VfSVA2EAMSDAoIVVNF",
            "X0lQNDYQBBIMCghVU0VfSVA2NBAFEgwKCEZPUkNFX0lQEAYSDQoJRk9SQ0Vf",
            "SVA0EAcSDQoJRk9SQ0VfSVA2EAgSDgoKRk9SQ0VfSVA0NhAJEg4KCkZPUkNF",
            "X0lQNjQQCkJYChZjb20ueHJheS5wcm94eS5mcmVlZG9tUAFaJ2dpdGh1Yi5j",
            "b20veHRscy94cmF5LWNvcmUvcHJveHkvZnJlZWRvbaoCElhyYXkuUHJveHku",
            "RnJlZWRvbWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Xray.Common.Protocol.ServerSpecReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.Proxy.Freedom.DestinationOverride), global::Xray.Proxy.Freedom.DestinationOverride.Parser, new[]{ "Server" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.Proxy.Freedom.Fragment), global::Xray.Proxy.Freedom.Fragment.Parser, new[]{ "PacketsFrom", "PacketsTo", "LengthMin", "LengthMax", "IntervalMin", "IntervalMax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.Proxy.Freedom.Noise), global::Xray.Proxy.Freedom.Noise.Parser, new[]{ "LengthMin", "LengthMax", "DelayMin", "DelayMax", "StrNoise" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.Proxy.Freedom.Config), global::Xray.Proxy.Freedom.Config.Parser, new[]{ "DomainStrategy", "DestinationOverride", "UserLevel", "Fragment", "ProxyProtocol", "Noises" }, null, new[]{ typeof(global::Xray.Proxy.Freedom.Config.Types.DomainStrategy) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DestinationOverride : pb::IMessage<DestinationOverride>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DestinationOverride> _parser = new pb::MessageParser<DestinationOverride>(() => new DestinationOverride());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DestinationOverride> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.Proxy.Freedom.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestinationOverride() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestinationOverride(DestinationOverride other) : this() {
      server_ = other.server_ != null ? other.server_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DestinationOverride Clone() {
      return new DestinationOverride(this);
    }

    /// <summary>Field number for the "server" field.</summary>
    public const int ServerFieldNumber = 1;
    private global::Xray.Common.Protocol.ServerEndpoint server_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.Common.Protocol.ServerEndpoint Server {
      get { return server_; }
      set {
        server_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DestinationOverride);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DestinationOverride other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Server, other.Server)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (server_ != null) hash ^= Server.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (server_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Server);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (server_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Server);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (server_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Server);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DestinationOverride other) {
      if (other == null) {
        return;
      }
      if (other.server_ != null) {
        if (server_ == null) {
          Server = new global::Xray.Common.Protocol.ServerEndpoint();
        }
        Server.MergeFrom(other.Server);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (server_ == null) {
              Server = new global::Xray.Common.Protocol.ServerEndpoint();
            }
            input.ReadMessage(Server);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (server_ == null) {
              Server = new global::Xray.Common.Protocol.ServerEndpoint();
            }
            input.ReadMessage(Server);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Fragment : pb::IMessage<Fragment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Fragment> _parser = new pb::MessageParser<Fragment>(() => new Fragment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Fragment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.Proxy.Freedom.ConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fragment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fragment(Fragment other) : this() {
      packetsFrom_ = other.packetsFrom_;
      packetsTo_ = other.packetsTo_;
      lengthMin_ = other.lengthMin_;
      lengthMax_ = other.lengthMax_;
      intervalMin_ = other.intervalMin_;
      intervalMax_ = other.intervalMax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Fragment Clone() {
      return new Fragment(this);
    }

    /// <summary>Field number for the "packets_from" field.</summary>
    public const int PacketsFromFieldNumber = 1;
    private ulong packetsFrom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PacketsFrom {
      get { return packetsFrom_; }
      set {
        packetsFrom_ = value;
      }
    }

    /// <summary>Field number for the "packets_to" field.</summary>
    public const int PacketsToFieldNumber = 2;
    private ulong packetsTo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PacketsTo {
      get { return packetsTo_; }
      set {
        packetsTo_ = value;
      }
    }

    /// <summary>Field number for the "length_min" field.</summary>
    public const int LengthMinFieldNumber = 3;
    private ulong lengthMin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LengthMin {
      get { return lengthMin_; }
      set {
        lengthMin_ = value;
      }
    }

    /// <summary>Field number for the "length_max" field.</summary>
    public const int LengthMaxFieldNumber = 4;
    private ulong lengthMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LengthMax {
      get { return lengthMax_; }
      set {
        lengthMax_ = value;
      }
    }

    /// <summary>Field number for the "interval_min" field.</summary>
    public const int IntervalMinFieldNumber = 5;
    private ulong intervalMin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong IntervalMin {
      get { return intervalMin_; }
      set {
        intervalMin_ = value;
      }
    }

    /// <summary>Field number for the "interval_max" field.</summary>
    public const int IntervalMaxFieldNumber = 6;
    private ulong intervalMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong IntervalMax {
      get { return intervalMax_; }
      set {
        intervalMax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Fragment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Fragment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PacketsFrom != other.PacketsFrom) return false;
      if (PacketsTo != other.PacketsTo) return false;
      if (LengthMin != other.LengthMin) return false;
      if (LengthMax != other.LengthMax) return false;
      if (IntervalMin != other.IntervalMin) return false;
      if (IntervalMax != other.IntervalMax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PacketsFrom != 0UL) hash ^= PacketsFrom.GetHashCode();
      if (PacketsTo != 0UL) hash ^= PacketsTo.GetHashCode();
      if (LengthMin != 0UL) hash ^= LengthMin.GetHashCode();
      if (LengthMax != 0UL) hash ^= LengthMax.GetHashCode();
      if (IntervalMin != 0UL) hash ^= IntervalMin.GetHashCode();
      if (IntervalMax != 0UL) hash ^= IntervalMax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PacketsFrom != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PacketsFrom);
      }
      if (PacketsTo != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PacketsTo);
      }
      if (LengthMin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(LengthMin);
      }
      if (LengthMax != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(LengthMax);
      }
      if (IntervalMin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(IntervalMin);
      }
      if (IntervalMax != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(IntervalMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PacketsFrom != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(PacketsFrom);
      }
      if (PacketsTo != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(PacketsTo);
      }
      if (LengthMin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(LengthMin);
      }
      if (LengthMax != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(LengthMax);
      }
      if (IntervalMin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(IntervalMin);
      }
      if (IntervalMax != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(IntervalMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PacketsFrom != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PacketsFrom);
      }
      if (PacketsTo != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PacketsTo);
      }
      if (LengthMin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LengthMin);
      }
      if (LengthMax != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LengthMax);
      }
      if (IntervalMin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(IntervalMin);
      }
      if (IntervalMax != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(IntervalMax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Fragment other) {
      if (other == null) {
        return;
      }
      if (other.PacketsFrom != 0UL) {
        PacketsFrom = other.PacketsFrom;
      }
      if (other.PacketsTo != 0UL) {
        PacketsTo = other.PacketsTo;
      }
      if (other.LengthMin != 0UL) {
        LengthMin = other.LengthMin;
      }
      if (other.LengthMax != 0UL) {
        LengthMax = other.LengthMax;
      }
      if (other.IntervalMin != 0UL) {
        IntervalMin = other.IntervalMin;
      }
      if (other.IntervalMax != 0UL) {
        IntervalMax = other.IntervalMax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PacketsFrom = input.ReadUInt64();
            break;
          }
          case 16: {
            PacketsTo = input.ReadUInt64();
            break;
          }
          case 24: {
            LengthMin = input.ReadUInt64();
            break;
          }
          case 32: {
            LengthMax = input.ReadUInt64();
            break;
          }
          case 40: {
            IntervalMin = input.ReadUInt64();
            break;
          }
          case 48: {
            IntervalMax = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PacketsFrom = input.ReadUInt64();
            break;
          }
          case 16: {
            PacketsTo = input.ReadUInt64();
            break;
          }
          case 24: {
            LengthMin = input.ReadUInt64();
            break;
          }
          case 32: {
            LengthMax = input.ReadUInt64();
            break;
          }
          case 40: {
            IntervalMin = input.ReadUInt64();
            break;
          }
          case 48: {
            IntervalMax = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Noise : pb::IMessage<Noise>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Noise> _parser = new pb::MessageParser<Noise>(() => new Noise());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Noise> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.Proxy.Freedom.ConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Noise() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Noise(Noise other) : this() {
      lengthMin_ = other.lengthMin_;
      lengthMax_ = other.lengthMax_;
      delayMin_ = other.delayMin_;
      delayMax_ = other.delayMax_;
      strNoise_ = other.strNoise_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Noise Clone() {
      return new Noise(this);
    }

    /// <summary>Field number for the "length_min" field.</summary>
    public const int LengthMinFieldNumber = 1;
    private ulong lengthMin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LengthMin {
      get { return lengthMin_; }
      set {
        lengthMin_ = value;
      }
    }

    /// <summary>Field number for the "length_max" field.</summary>
    public const int LengthMaxFieldNumber = 2;
    private ulong lengthMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LengthMax {
      get { return lengthMax_; }
      set {
        lengthMax_ = value;
      }
    }

    /// <summary>Field number for the "delay_min" field.</summary>
    public const int DelayMinFieldNumber = 3;
    private ulong delayMin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DelayMin {
      get { return delayMin_; }
      set {
        delayMin_ = value;
      }
    }

    /// <summary>Field number for the "delay_max" field.</summary>
    public const int DelayMaxFieldNumber = 4;
    private ulong delayMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong DelayMax {
      get { return delayMax_; }
      set {
        delayMax_ = value;
      }
    }

    /// <summary>Field number for the "str_noise" field.</summary>
    public const int StrNoiseFieldNumber = 5;
    private pb::ByteString strNoise_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString StrNoise {
      get { return strNoise_; }
      set {
        strNoise_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Noise);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Noise other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LengthMin != other.LengthMin) return false;
      if (LengthMax != other.LengthMax) return false;
      if (DelayMin != other.DelayMin) return false;
      if (DelayMax != other.DelayMax) return false;
      if (StrNoise != other.StrNoise) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LengthMin != 0UL) hash ^= LengthMin.GetHashCode();
      if (LengthMax != 0UL) hash ^= LengthMax.GetHashCode();
      if (DelayMin != 0UL) hash ^= DelayMin.GetHashCode();
      if (DelayMax != 0UL) hash ^= DelayMax.GetHashCode();
      if (StrNoise.Length != 0) hash ^= StrNoise.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LengthMin != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LengthMin);
      }
      if (LengthMax != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(LengthMax);
      }
      if (DelayMin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(DelayMin);
      }
      if (DelayMax != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(DelayMax);
      }
      if (StrNoise.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(StrNoise);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LengthMin != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LengthMin);
      }
      if (LengthMax != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(LengthMax);
      }
      if (DelayMin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(DelayMin);
      }
      if (DelayMax != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(DelayMax);
      }
      if (StrNoise.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(StrNoise);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LengthMin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LengthMin);
      }
      if (LengthMax != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LengthMax);
      }
      if (DelayMin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DelayMin);
      }
      if (DelayMax != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DelayMax);
      }
      if (StrNoise.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(StrNoise);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Noise other) {
      if (other == null) {
        return;
      }
      if (other.LengthMin != 0UL) {
        LengthMin = other.LengthMin;
      }
      if (other.LengthMax != 0UL) {
        LengthMax = other.LengthMax;
      }
      if (other.DelayMin != 0UL) {
        DelayMin = other.DelayMin;
      }
      if (other.DelayMax != 0UL) {
        DelayMax = other.DelayMax;
      }
      if (other.StrNoise.Length != 0) {
        StrNoise = other.StrNoise;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LengthMin = input.ReadUInt64();
            break;
          }
          case 16: {
            LengthMax = input.ReadUInt64();
            break;
          }
          case 24: {
            DelayMin = input.ReadUInt64();
            break;
          }
          case 32: {
            DelayMax = input.ReadUInt64();
            break;
          }
          case 42: {
            StrNoise = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LengthMin = input.ReadUInt64();
            break;
          }
          case 16: {
            LengthMax = input.ReadUInt64();
            break;
          }
          case 24: {
            DelayMin = input.ReadUInt64();
            break;
          }
          case 32: {
            DelayMax = input.ReadUInt64();
            break;
          }
          case 42: {
            StrNoise = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.Proxy.Freedom.ConfigReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config(Config other) : this() {
      domainStrategy_ = other.domainStrategy_;
      destinationOverride_ = other.destinationOverride_ != null ? other.destinationOverride_.Clone() : null;
      userLevel_ = other.userLevel_;
      fragment_ = other.fragment_ != null ? other.fragment_.Clone() : null;
      proxyProtocol_ = other.proxyProtocol_;
      noises_ = other.noises_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "domain_strategy" field.</summary>
    public const int DomainStrategyFieldNumber = 1;
    private global::Xray.Proxy.Freedom.Config.Types.DomainStrategy domainStrategy_ = global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.Proxy.Freedom.Config.Types.DomainStrategy DomainStrategy {
      get { return domainStrategy_; }
      set {
        domainStrategy_ = value;
      }
    }

    /// <summary>Field number for the "destination_override" field.</summary>
    public const int DestinationOverrideFieldNumber = 3;
    private global::Xray.Proxy.Freedom.DestinationOverride destinationOverride_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.Proxy.Freedom.DestinationOverride DestinationOverride {
      get { return destinationOverride_; }
      set {
        destinationOverride_ = value;
      }
    }

    /// <summary>Field number for the "user_level" field.</summary>
    public const int UserLevelFieldNumber = 4;
    private uint userLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UserLevel {
      get { return userLevel_; }
      set {
        userLevel_ = value;
      }
    }

    /// <summary>Field number for the "fragment" field.</summary>
    public const int FragmentFieldNumber = 5;
    private global::Xray.Proxy.Freedom.Fragment fragment_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.Proxy.Freedom.Fragment Fragment {
      get { return fragment_; }
      set {
        fragment_ = value;
      }
    }

    /// <summary>Field number for the "proxy_protocol" field.</summary>
    public const int ProxyProtocolFieldNumber = 6;
    private uint proxyProtocol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProxyProtocol {
      get { return proxyProtocol_; }
      set {
        proxyProtocol_ = value;
      }
    }

    /// <summary>Field number for the "noises" field.</summary>
    public const int NoisesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Xray.Proxy.Freedom.Noise> _repeated_noises_codec
        = pb::FieldCodec.ForMessage(58, global::Xray.Proxy.Freedom.Noise.Parser);
    private readonly pbc::RepeatedField<global::Xray.Proxy.Freedom.Noise> noises_ = new pbc::RepeatedField<global::Xray.Proxy.Freedom.Noise>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Xray.Proxy.Freedom.Noise> Noises {
      get { return noises_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DomainStrategy != other.DomainStrategy) return false;
      if (!object.Equals(DestinationOverride, other.DestinationOverride)) return false;
      if (UserLevel != other.UserLevel) return false;
      if (!object.Equals(Fragment, other.Fragment)) return false;
      if (ProxyProtocol != other.ProxyProtocol) return false;
      if(!noises_.Equals(other.noises_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DomainStrategy != global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs) hash ^= DomainStrategy.GetHashCode();
      if (destinationOverride_ != null) hash ^= DestinationOverride.GetHashCode();
      if (UserLevel != 0) hash ^= UserLevel.GetHashCode();
      if (fragment_ != null) hash ^= Fragment.GetHashCode();
      if (ProxyProtocol != 0) hash ^= ProxyProtocol.GetHashCode();
      hash ^= noises_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DomainStrategy != global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DomainStrategy);
      }
      if (destinationOverride_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DestinationOverride);
      }
      if (UserLevel != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UserLevel);
      }
      if (fragment_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Fragment);
      }
      if (ProxyProtocol != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ProxyProtocol);
      }
      noises_.WriteTo(output, _repeated_noises_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DomainStrategy != global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DomainStrategy);
      }
      if (destinationOverride_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DestinationOverride);
      }
      if (UserLevel != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UserLevel);
      }
      if (fragment_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Fragment);
      }
      if (ProxyProtocol != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ProxyProtocol);
      }
      noises_.WriteTo(ref output, _repeated_noises_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DomainStrategy != global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DomainStrategy);
      }
      if (destinationOverride_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DestinationOverride);
      }
      if (UserLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserLevel);
      }
      if (fragment_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fragment);
      }
      if (ProxyProtocol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProxyProtocol);
      }
      size += noises_.CalculateSize(_repeated_noises_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.DomainStrategy != global::Xray.Proxy.Freedom.Config.Types.DomainStrategy.AsIs) {
        DomainStrategy = other.DomainStrategy;
      }
      if (other.destinationOverride_ != null) {
        if (destinationOverride_ == null) {
          DestinationOverride = new global::Xray.Proxy.Freedom.DestinationOverride();
        }
        DestinationOverride.MergeFrom(other.DestinationOverride);
      }
      if (other.UserLevel != 0) {
        UserLevel = other.UserLevel;
      }
      if (other.fragment_ != null) {
        if (fragment_ == null) {
          Fragment = new global::Xray.Proxy.Freedom.Fragment();
        }
        Fragment.MergeFrom(other.Fragment);
      }
      if (other.ProxyProtocol != 0) {
        ProxyProtocol = other.ProxyProtocol;
      }
      noises_.Add(other.noises_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DomainStrategy = (global::Xray.Proxy.Freedom.Config.Types.DomainStrategy) input.ReadEnum();
            break;
          }
          case 26: {
            if (destinationOverride_ == null) {
              DestinationOverride = new global::Xray.Proxy.Freedom.DestinationOverride();
            }
            input.ReadMessage(DestinationOverride);
            break;
          }
          case 32: {
            UserLevel = input.ReadUInt32();
            break;
          }
          case 42: {
            if (fragment_ == null) {
              Fragment = new global::Xray.Proxy.Freedom.Fragment();
            }
            input.ReadMessage(Fragment);
            break;
          }
          case 48: {
            ProxyProtocol = input.ReadUInt32();
            break;
          }
          case 58: {
            noises_.AddEntriesFrom(input, _repeated_noises_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DomainStrategy = (global::Xray.Proxy.Freedom.Config.Types.DomainStrategy) input.ReadEnum();
            break;
          }
          case 26: {
            if (destinationOverride_ == null) {
              DestinationOverride = new global::Xray.Proxy.Freedom.DestinationOverride();
            }
            input.ReadMessage(DestinationOverride);
            break;
          }
          case 32: {
            UserLevel = input.ReadUInt32();
            break;
          }
          case 42: {
            if (fragment_ == null) {
              Fragment = new global::Xray.Proxy.Freedom.Fragment();
            }
            input.ReadMessage(Fragment);
            break;
          }
          case 48: {
            ProxyProtocol = input.ReadUInt32();
            break;
          }
          case 58: {
            noises_.AddEntriesFrom(ref input, _repeated_noises_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Config message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum DomainStrategy {
        [pbr::OriginalName("AS_IS")] AsIs = 0,
        [pbr::OriginalName("USE_IP")] UseIp = 1,
        [pbr::OriginalName("USE_IP4")] UseIp4 = 2,
        [pbr::OriginalName("USE_IP6")] UseIp6 = 3,
        [pbr::OriginalName("USE_IP46")] UseIp46 = 4,
        [pbr::OriginalName("USE_IP64")] UseIp64 = 5,
        [pbr::OriginalName("FORCE_IP")] ForceIp = 6,
        [pbr::OriginalName("FORCE_IP4")] ForceIp4 = 7,
        [pbr::OriginalName("FORCE_IP6")] ForceIp6 = 8,
        [pbr::OriginalName("FORCE_IP46")] ForceIp46 = 9,
        [pbr::OriginalName("FORCE_IP64")] ForceIp64 = 10,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
