// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: transport/internet/http/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xray.Transport.Internet.Http {

  /// <summary>Holder for reflection information generated from transport/internet/http/config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for transport/internet/http/config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiR0cmFuc3BvcnQvaW50ZXJuZXQvaHR0cC9jb25maWcucHJvdG8SHHhyYXku",
            "dHJhbnNwb3J0LmludGVybmV0Lmh0dHAaLHRyYW5zcG9ydC9pbnRlcm5ldC9o",
            "ZWFkZXJzL2h0dHAvY29uZmlnLnByb3RvIqYBCgZDb25maWcSDAoEaG9zdBgB",
            "IAMoCRIMCgRwYXRoGAIgASgJEhQKDGlkbGVfdGltZW91dBgDIAEoBRIcChRo",
            "ZWFsdGhfY2hlY2tfdGltZW91dBgEIAEoBRIOCgZtZXRob2QYBSABKAkSPAoG",
            "aGVhZGVyGAYgAygLMiwueHJheS50cmFuc3BvcnQuaW50ZXJuZXQuaGVhZGVy",
            "cy5odHRwLkhlYWRlckJ2CiBjb20ueHJheS50cmFuc3BvcnQuaW50ZXJuZXQu",
            "aHR0cFABWjFnaXRodWIuY29tL3h0bHMveHJheS1jb3JlL3RyYW5zcG9ydC9p",
            "bnRlcm5ldC9odHRwqgIcWHJheS5UcmFuc3BvcnQuSW50ZXJuZXQuSHR0cGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Xray.Transport.Internet.Headers.Http.ConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.Transport.Internet.Http.Config), global::Xray.Transport.Internet.Http.Config.Parser, new[]{ "Host", "Path", "IdleTimeout", "HealthCheckTimeout", "Method", "Header" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.Transport.Internet.Http.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config(Config other) : this() {
      host_ = other.host_.Clone();
      path_ = other.path_;
      idleTimeout_ = other.idleTimeout_;
      healthCheckTimeout_ = other.healthCheckTimeout_;
      method_ = other.method_;
      header_ = other.header_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "host" field.</summary>
    public const int HostFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_host_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> host_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Host {
      get { return host_; }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 2;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "idle_timeout" field.</summary>
    public const int IdleTimeoutFieldNumber = 3;
    private int idleTimeout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdleTimeout {
      get { return idleTimeout_; }
      set {
        idleTimeout_ = value;
      }
    }

    /// <summary>Field number for the "health_check_timeout" field.</summary>
    public const int HealthCheckTimeoutFieldNumber = 4;
    private int healthCheckTimeout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HealthCheckTimeout {
      get { return healthCheckTimeout_; }
      set {
        healthCheckTimeout_ = value;
      }
    }

    /// <summary>Field number for the "method" field.</summary>
    public const int MethodFieldNumber = 5;
    private string method_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Method {
      get { return method_; }
      set {
        method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Xray.Transport.Internet.Headers.Http.Header> _repeated_header_codec
        = pb::FieldCodec.ForMessage(50, global::Xray.Transport.Internet.Headers.Http.Header.Parser);
    private readonly pbc::RepeatedField<global::Xray.Transport.Internet.Headers.Http.Header> header_ = new pbc::RepeatedField<global::Xray.Transport.Internet.Headers.Http.Header>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Xray.Transport.Internet.Headers.Http.Header> Header {
      get { return header_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!host_.Equals(other.host_)) return false;
      if (Path != other.Path) return false;
      if (IdleTimeout != other.IdleTimeout) return false;
      if (HealthCheckTimeout != other.HealthCheckTimeout) return false;
      if (Method != other.Method) return false;
      if(!header_.Equals(other.header_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= host_.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (IdleTimeout != 0) hash ^= IdleTimeout.GetHashCode();
      if (HealthCheckTimeout != 0) hash ^= HealthCheckTimeout.GetHashCode();
      if (Method.Length != 0) hash ^= Method.GetHashCode();
      hash ^= header_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      host_.WriteTo(output, _repeated_host_codec);
      if (Path.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Path);
      }
      if (IdleTimeout != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdleTimeout);
      }
      if (HealthCheckTimeout != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(HealthCheckTimeout);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Method);
      }
      header_.WriteTo(output, _repeated_header_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      host_.WriteTo(ref output, _repeated_host_codec);
      if (Path.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Path);
      }
      if (IdleTimeout != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdleTimeout);
      }
      if (HealthCheckTimeout != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(HealthCheckTimeout);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Method);
      }
      header_.WriteTo(ref output, _repeated_header_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += host_.CalculateSize(_repeated_host_codec);
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (IdleTimeout != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdleTimeout);
      }
      if (HealthCheckTimeout != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HealthCheckTimeout);
      }
      if (Method.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
      }
      size += header_.CalculateSize(_repeated_header_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      host_.Add(other.host_);
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      if (other.IdleTimeout != 0) {
        IdleTimeout = other.IdleTimeout;
      }
      if (other.HealthCheckTimeout != 0) {
        HealthCheckTimeout = other.HealthCheckTimeout;
      }
      if (other.Method.Length != 0) {
        Method = other.Method;
      }
      header_.Add(other.header_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            host_.AddEntriesFrom(input, _repeated_host_codec);
            break;
          }
          case 18: {
            Path = input.ReadString();
            break;
          }
          case 24: {
            IdleTimeout = input.ReadInt32();
            break;
          }
          case 32: {
            HealthCheckTimeout = input.ReadInt32();
            break;
          }
          case 42: {
            Method = input.ReadString();
            break;
          }
          case 50: {
            header_.AddEntriesFrom(input, _repeated_header_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            host_.AddEntriesFrom(ref input, _repeated_host_codec);
            break;
          }
          case 18: {
            Path = input.ReadString();
            break;
          }
          case 24: {
            IdleTimeout = input.ReadInt32();
            break;
          }
          case 32: {
            HealthCheckTimeout = input.ReadInt32();
            break;
          }
          case 42: {
            Method = input.ReadString();
            break;
          }
          case 50: {
            header_.AddEntriesFrom(ref input, _repeated_header_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
