// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: app/observatory/burst/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Xray.App.Observatory.Burst {

  /// <summary>Holder for reflection information generated from app/observatory/burst/config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for app/observatory/burst/config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhcHAvb2JzZXJ2YXRvcnkvYnVyc3QvY29uZmlnLnByb3RvEh94cmF5LmNv",
            "cmUuYXBwLm9ic2VydmF0b3J5LmJ1cnN0ImoKBkNvbmZpZxIYChBzdWJqZWN0",
            "X3NlbGVjdG9yGAIgAygJEkYKC3BpbmdfY29uZmlnGAMgASgLMjEueHJheS5j",
            "b3JlLmFwcC5vYnNlcnZhdG9yeS5idXJzdC5IZWFsdGhQaW5nQ29uZmlnIncK",
            "EEhlYWx0aFBpbmdDb25maWcSEwoLZGVzdGluYXRpb24YASABKAkSFAoMY29u",
            "bmVjdGl2aXR5GAIgASgJEhAKCGludGVydmFsGAMgASgDEhUKDXNhbXBsaW5n",
            "Q291bnQYBCABKAUSDwoHdGltZW91dBgFIAEoA0JwCh5jb20ueHJheS5hcHAu",
            "b2JzZXJ2YXRvcnkuYnVyc3RQAVovZ2l0aHViLmNvbS94dGxzL3hyYXktY29y",
            "ZS9hcHAvb2JzZXJ2YXRvcnkvYnVyc3SqAhpYcmF5LkFwcC5PYnNlcnZhdG9y",
            "eS5CdXJzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.App.Observatory.Burst.Config), global::Xray.App.Observatory.Burst.Config.Parser, new[]{ "SubjectSelector", "PingConfig" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Xray.App.Observatory.Burst.HealthPingConfig), global::Xray.App.Observatory.Burst.HealthPingConfig.Parser, new[]{ "Destination", "Connectivity", "Interval", "SamplingCount", "Timeout" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.App.Observatory.Burst.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config(Config other) : this() {
      subjectSelector_ = other.subjectSelector_.Clone();
      pingConfig_ = other.pingConfig_ != null ? other.pingConfig_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "subject_selector" field.</summary>
    public const int SubjectSelectorFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_subjectSelector_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> subjectSelector_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// @Document The selectors for outbound under observation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> SubjectSelector {
      get { return subjectSelector_; }
    }

    /// <summary>Field number for the "ping_config" field.</summary>
    public const int PingConfigFieldNumber = 3;
    private global::Xray.App.Observatory.Burst.HealthPingConfig pingConfig_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Xray.App.Observatory.Burst.HealthPingConfig PingConfig {
      get { return pingConfig_; }
      set {
        pingConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!subjectSelector_.Equals(other.subjectSelector_)) return false;
      if (!object.Equals(PingConfig, other.PingConfig)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= subjectSelector_.GetHashCode();
      if (pingConfig_ != null) hash ^= PingConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      subjectSelector_.WriteTo(output, _repeated_subjectSelector_codec);
      if (pingConfig_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PingConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      subjectSelector_.WriteTo(ref output, _repeated_subjectSelector_codec);
      if (pingConfig_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PingConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += subjectSelector_.CalculateSize(_repeated_subjectSelector_codec);
      if (pingConfig_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PingConfig);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      subjectSelector_.Add(other.subjectSelector_);
      if (other.pingConfig_ != null) {
        if (pingConfig_ == null) {
          PingConfig = new global::Xray.App.Observatory.Burst.HealthPingConfig();
        }
        PingConfig.MergeFrom(other.PingConfig);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            subjectSelector_.AddEntriesFrom(input, _repeated_subjectSelector_codec);
            break;
          }
          case 26: {
            if (pingConfig_ == null) {
              PingConfig = new global::Xray.App.Observatory.Burst.HealthPingConfig();
            }
            input.ReadMessage(PingConfig);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            subjectSelector_.AddEntriesFrom(ref input, _repeated_subjectSelector_codec);
            break;
          }
          case 26: {
            if (pingConfig_ == null) {
              PingConfig = new global::Xray.App.Observatory.Burst.HealthPingConfig();
            }
            input.ReadMessage(PingConfig);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HealthPingConfig : pb::IMessage<HealthPingConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HealthPingConfig> _parser = new pb::MessageParser<HealthPingConfig>(() => new HealthPingConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HealthPingConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Xray.App.Observatory.Burst.ConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthPingConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthPingConfig(HealthPingConfig other) : this() {
      destination_ = other.destination_;
      connectivity_ = other.connectivity_;
      interval_ = other.interval_;
      samplingCount_ = other.samplingCount_;
      timeout_ = other.timeout_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthPingConfig Clone() {
      return new HealthPingConfig(this);
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 1;
    private string destination_ = "";
    /// <summary>
    /// destination url, need 204 for success return
    /// default https://connectivitycheck.gstatic.com/generate_204
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "connectivity" field.</summary>
    public const int ConnectivityFieldNumber = 2;
    private string connectivity_ = "";
    /// <summary>
    /// connectivity check url
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Connectivity {
      get { return connectivity_; }
      set {
        connectivity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "interval" field.</summary>
    public const int IntervalFieldNumber = 3;
    private long interval_;
    /// <summary>
    /// health check interval, int64 values of time.Duration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    /// <summary>Field number for the "samplingCount" field.</summary>
    public const int SamplingCountFieldNumber = 4;
    private int samplingCount_;
    /// <summary>
    /// sampling count is the amount of recent ping results which are kept for calculation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SamplingCount {
      get { return samplingCount_; }
      set {
        samplingCount_ = value;
      }
    }

    /// <summary>Field number for the "timeout" field.</summary>
    public const int TimeoutFieldNumber = 5;
    private long timeout_;
    /// <summary>
    /// ping timeout, int64 values of time.Duration
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timeout {
      get { return timeout_; }
      set {
        timeout_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HealthPingConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HealthPingConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Destination != other.Destination) return false;
      if (Connectivity != other.Connectivity) return false;
      if (Interval != other.Interval) return false;
      if (SamplingCount != other.SamplingCount) return false;
      if (Timeout != other.Timeout) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (Connectivity.Length != 0) hash ^= Connectivity.GetHashCode();
      if (Interval != 0L) hash ^= Interval.GetHashCode();
      if (SamplingCount != 0) hash ^= SamplingCount.GetHashCode();
      if (Timeout != 0L) hash ^= Timeout.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (Connectivity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Connectivity);
      }
      if (Interval != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Interval);
      }
      if (SamplingCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SamplingCount);
      }
      if (Timeout != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timeout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (Connectivity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Connectivity);
      }
      if (Interval != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Interval);
      }
      if (SamplingCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SamplingCount);
      }
      if (Timeout != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timeout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (Connectivity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Connectivity);
      }
      if (Interval != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Interval);
      }
      if (SamplingCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SamplingCount);
      }
      if (Timeout != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timeout);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HealthPingConfig other) {
      if (other == null) {
        return;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.Connectivity.Length != 0) {
        Connectivity = other.Connectivity;
      }
      if (other.Interval != 0L) {
        Interval = other.Interval;
      }
      if (other.SamplingCount != 0) {
        SamplingCount = other.SamplingCount;
      }
      if (other.Timeout != 0L) {
        Timeout = other.Timeout;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            Connectivity = input.ReadString();
            break;
          }
          case 24: {
            Interval = input.ReadInt64();
            break;
          }
          case 32: {
            SamplingCount = input.ReadInt32();
            break;
          }
          case 40: {
            Timeout = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            Connectivity = input.ReadString();
            break;
          }
          case 24: {
            Interval = input.ReadInt64();
            break;
          }
          case 32: {
            SamplingCount = input.ReadInt32();
            break;
          }
          case 40: {
            Timeout = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
